function aula (){
    //enquanto() faca ...
    // para condição ate condição2
    var i = 0;

    while (i < 10) {
        console.log (i)
        i++
    }
     while (false) {
        var pergunta = comfirm("repete?")

        if (pergunta = false){
            break;
    }
}
for(var i; i<100;i++){
    document.querySelector('main').innerHTML=
    `<p> SOU TOP</P>
    <p> SOU TOP</P>
    `;
}
do{
    console.log(i);
    i++
}while(i>10)
}
aula();