Algoritmo "semnome"

Var
NOME : caractere
produtos : vetor[1..4] de caractere
numeros : vetor [1..3] de inteiro
i : inteiro

Inicio
NOME <- "Victor"
NOME <- "Alessandro"

 produtos[1]<- "Banana"
 produtos[2] <- "Salgadinho"
 produtos[3]<-"Refrigerante"
 produtos[4]<-"Café"

  para i <- 1 até 3 faca
  leia(numeros[i])
 fimPara
 
 para i <- 1 até 3 faca
 escreval ("n",i,"°", numeros[i])
 fimPara
Fimalgoritmo